In [10]:
#Create a NumPy array from a list
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [11]:
#Create a 2D NumPy array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [12]:
#Find the shape of an array
print(arr2.shape)

(2, 3)


In [13]:
#Find the data type of elements
print(arr2.dtype)

int64


In [15]:
#Create an array of zeros
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
#Create an array of ones
ones = np.ones((2,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
#Create an array with a range of numbers
range_arr = np.arange(1,10,2)
print(range_arr)

[1 3 5 7 9]


In [22]:
#Create an array of ones
ones = np.ones((4,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
#Create an array with evenly spaced values
lin = np.linspace(0,1,20)
print(lin)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [26]:
#Reshape an array
arr = np.arange(6).reshape(2,3)
print(arr)

[[0 1 2]
 [3 4 5]]


In [27]:
#Flatten a multidimensional array
flat = arr.flatten()
print(flat)

[0 1 2 3 4 5]


In [28]:
#Find maximum and minimum values
print(arr.max())
print(arr.min())

5
0


In [29]:
#Find the sum of all elements
print(arr.sum())

15


In [35]:
#Find mean, median, and standard deviation
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

2.5
2.5
1.707825127659933


In [36]:
#Slice an array
print(arr2[:,1])

[2 5]


In [37]:
#Access specific element in a 2D array
print(arr2[1,2])

6


In [39]:
#Perform element-wise addition
a = np.array([1,8,7])
b = np.array([4,5,6])
print(a + b)

[ 5 13 13]


In [42]:
#Perform element-wise multiplication
a = np.array([1,8,7])
b = np.array([4,5,6])
print(a * b)

[ 4 40 42]


In [41]:
#Matrix multiplication
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
print(np.dot(mat1, mat2))

[[19 22]
 [43 50]]


In [43]:
#transpose of a matrix
print(mat1.T)

[[1 3]
 [2 4]]


In [51]:
#Find unique elements in array
arr = np.array([1,2,2,3,3,3])
print(np.unique(arr))

[1 2 3]


In [50]:
#boolean indexing
arr = np.array([10,20,30,40])
print(arr[arr>20])

[30 40]


In [52]:
#Replace elements based on condition
arr[arr>25] = 0
print(arr)

[1 2 2 3 3 3]


In [53]:
#Generate random integers.
rand_int = np.random.randint(1,10,5)
print(rand_int)

[7 4 7 9 2]


In [58]:
#random float
rand_float = np.random.rand(3,2)
print(rand_float)

[[0.51287967 0.49929174]
 [0.96219112 0.62070816]
 [0.31954449 0.96443126]]


In [59]:
#Shuffle elements of an array
arr = np.arange(10)
np.random.shuffle(arr)
print(arr)

[1 6 9 2 0 3 8 7 5 4]


In [60]:
#sort an array
arr = np.array([4,1,3,2])
print(np.sort(arr))

[1 2 3 4]


In [61]:
#Stack arrays vertically.
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]]


In [62]:
#Stack arrays horizontally.
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [63]:
#Find correlation coefficient.
x = np.array([1,2,3])
y = np.array([1,5,7])
print(np.corrcoef(x,y))

[[1.         0.98198051]
 [0.98198051 1.        ]]


In [64]:
np.save('array.npy',arr)
loaded=np.load('array.npy')
print(loaded)


[4 1 3 2]
